//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinamaLib1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.ScheduleItem = new HashSet<ScheduleItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Actor { get; set; }
        public string MovieType { get; set; }
        public string Poster { get; set; }
        public double FullPrice { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleItem> ScheduleItem { get; set; }
        public virtual Customer ProcessedMovie { get; set; }
    }
}
