//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinamaLib1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleItem()
        {
            this.TicketsItem = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public int MovieItemId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Movie MovieItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> TicketsItem { get; set; }
        public virtual Customer ProcessedScheduleItem { get; set; }
    }
}
