//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinamaLib1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public string TicketType { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Coupon { get; set; }
        public int ScheduleItemId { get; set; }
        public int SeatItemId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ScheduleItem ScheduleItem { get; set; }
        public virtual Seat SeatItem { get; set; }
        public virtual Customer ProcessedTicket { get; set; }
    }
}
